name: notes-app E2E Tests
on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Create .env file
        working-directory: ./notes-app
        run: |
          touch .env
          echo USERNAME=${{ secrets.REGULAR_USER}} > .env
          echo PASSWORD=${{ secrets.REGULAR_PASS}} > .env
      - name: Install dependencies
        working-directory: ./notes-app
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./notes-app
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./notes-app
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./notes-app/playwright-report/
          retention-days: 30
